const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const DAYS = [["M","Monday"],["T","Tuesday"],["W","Wednesday"],["R","Thursday"],["F","Friday"]];
const START_MIN = 8 * 60, END_MIN = 20 * 60, STEP = 30;
let data = null, baselineData = null, currentView = "instructor", currentResource = "", busy = false, dragged = null, dirty = false, contextTarget = null, nextNewInstructorNumber = 1, nextNewProfessorNumber = 1;
let currentWorkspace="configuration",configurationFiles=[],configurationPackages=[],selectedConfigurationName="",selectedConfigurationPackage="",configurationDirty=false,analysisTimer=null;

function selectedPackage(){return $("#packageSelect")?.value||"27S";}
function managedPackage(){return $("#configurationPackageSelect")?.value||selectedConfigurationPackage||selectedPackage();}
function selectedPackageReady(){return configurationPackages.find(item=>item.id===selectedPackage())?.status==="ready";}
async function loadPackages(preferredManaged=""){try{const previousSchedule=selectedPackage(),previousManaged=preferredManaged||managedPackage(),response=await fetch("/api/configurations");const body=await response.json();if(!response.ok)throw new Error("Unable to load configuration packages");configurationPackages=body.configurations||[];const ready=configurationPackages.filter(item=>item.status==="ready");$("#packageSelect").innerHTML=ready.map(item=>`<option value="${esc(item.id)}">${esc(item.display_name)}</option>`).join("");if(ready.some(item=>item.id===previousSchedule))$("#packageSelect").value=previousSchedule;$("#configurationPackageSelect").innerHTML=configurationPackages.map(item=>`<option value="${esc(item.id)}">${esc(item.display_name)} · ${item.status[0].toUpperCase()+item.status.slice(1)}</option>`).join("");if(configurationPackages.some(item=>item.id===previousManaged))$("#configurationPackageSelect").value=previousManaged;selectedConfigurationPackage=managedPackage();$("#termInput").value=selectedPackage();renderWorkspaceTabs();setBusy(busy);}catch(error){toast(error.message,true);}}

document.body.insertAdjacentHTML("beforeend",`<div id="slotContextMenu" class="context-menu hidden" role="dialog" aria-label="Class assignment menu"><div class="context-title"><strong id="contextCourse"></strong><small id="contextSlot"></small></div><label class="context-field"><span>Assign instructor</span><div class="context-row"><select id="contextTeacher"></select><button id="assignTeacher">Assign</button><button id="newInstructor">New Instructor</button><button id="newProfessor">New Professor</button></div></label><label class="context-field"><span>Assign room</span><div class="context-row"><select id="contextRoom"></select><button id="assignRoom">Assign</button></div></label><small class="context-hint">Instructor changes apply to the atomic class; room changes apply to the selected meeting.</small></div>`);

function esc(v){return String(v ?? "—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function roomLabel(r){return [r.Building,r.Room].filter(Boolean).join(" ") || "Unassigned";}
function courseId(r){return `${r.Subject} ${r.Number}-${r.Section}`;}
function instructorLabel(name){return String(name||"Unassigned").replace(/^(?:Staff|new_instructor)(?=\s|$)/i,"New Instructor").replace(/^new_professor(?=\s|$)/i,"New Professor");}
function uiText(value){return String(value??"").replace(/\b(?:Staff|new_instructor)(?=\s|$)/gi,"New Instructor").replace(/\bnew_professor(?=\s|$)/gi,"New Professor");}
function isNewInstructor(name){return /^(?:Staff|new_instructor)(?:\s|$)/i.test(String(name||""));}
function isNewProfessor(name){return /^new_professor(?:\s|$)/i.test(String(name||""));}
function newInstructorName(rank){return rank===1?"new_instructor":`new_instructor ${rank}`;}
function newProfessorName(rank){return rank===1?"new_professor":`new_professor ${rank}`;}
function sections(){return data?.classes.flatMap((item,classIndex)=>item.sections.map((row,recordIndex)=>({...row,_item:item,_classIndex:classIndex,_recordIndex:recordIndex,_id:`${classIndex}:${recordIndex}`,course_id:courseId(row),credit_hours:item.credit_hours}))) || [];}
function displaySections(){const output=[];data?.classes.forEach((item,classIndex)=>{let rows=item.sections.map((row,recordIndex)=>({...row,_item:item,_classIndex:classIndex,_recordIndex:recordIndex,_id:`${classIndex}:${recordIndex}`,course_id:courseId(row),credit_hours:item.credit_hours}));if(item.kind==="HybridClass")rows=rows.filter(row=>startOf(row)!=null);if(item.kind==="CrossListingClass"){const groups=new Map;for(const row of rows){const key=[row.Instructor,row["Time Slot"],row.Building,row.Room].join("::");if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}rows=[...groups.values()].map(group=>({...group[0],display_course_id:group.map(row=>row.course_id).join(" / ")}));}output.push(...rows);});return output;}
function parseTime(value){if(!value)return null; if(typeof value==="string"){const m=value.match(/(\d{1,2}):(\d{2})/);if(m)return +m[1]*60 + +m[2];}return null;}
function startOf(r){return parseTime(r.Start) ?? parseTime(r["Time Slot"]);}
function daysOf(r){return r.Days || String(r["Time Slot"]||"").split(/\s+/)[0] || "";}
function clock(m){const h=Math.floor(m/60),mm=m%60;return `${h%12||12}:${String(mm).padStart(2,"0")} ${h<12?"AM":"PM"}`;}
function recordClock(minute){const normalized=((minute%1440)+1440)%1440,hour=Math.floor(normalized/60),minutes=normalized%60;return `${hour%12||12}:${String(minutes).padStart(2,"0")}${hour<12?"am":"pm"}`;}
function slotValue(days,minute){return `${days} ${recordClock(minute)}`;}

function setBusy(on,label){busy=on;const usable=selectedPackageReady();$("#packageSelect").disabled=on;$("#solveButton").disabled=on||!data||!usable;$("#saveButton").disabled=on||!data||!dirty||!usable;if(label)$("#solveButton").textContent=label;}
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.className=`toast${error?" error":""}`;setTimeout(()=>el.classList.add("hidden"),2600);}
$(".configuration-heading-actions").insertAdjacentHTML("afterbegin",`<label class="package-control"><span>Manage package</span><select id="configurationPackageSelect" aria-label="Configuration package to manage"></select></label>`);
$("#configurationProblems").insertAdjacentHTML("afterend",`<section class="configuration-template"><div><span class="kicker">SCHEDULE TEMPLATE</span><strong id="configurationTemplateName">No template</strong><small id="configurationTemplateStatus">No working views generated</small></div><label class="config-upload-button"><input id="configurationTemplateInput" type="file" accept=".csv,.xlsx">Replace Template</label><button id="configurationTemplateDownload" disabled>Download</button><button id="configurationTemplateDelete" class="danger-button" disabled>Delete</button><button id="configurationTemplateInfer" disabled>从模板推断</button><button id="configurationTemplateRebuild">Rebuild Working Views</button></section><section id="configurationDifferences" class="configuration-differences"><div class="configuration-differences-heading"><div><span class="kicker">TEMPLATE / COURSES DIFFERENCES</span><strong>模板与课程配置差异</strong></div><span id="configurationDifferenceCount">—</span></div><div id="configurationDifferenceBody" class="configuration-difference-body"></div></section>`);
initializeSchedule();
$("#configurationPackageSelect").addEventListener("change",()=>{selectedConfigurationPackage=managedPackage();loadConfigurationFiles();});

async function initializeSchedule(){applyWorkspaceVisibility();await loadPackages();await loadConfigurationFiles();}
function showScheduleUnavailable(message){data=null;baselineData=null;dirty=false;$("#app").classList.add("hidden");$("#emptyState").classList.remove("hidden");$("#emptyState h1").textContent="Schedule unavailable";$("#emptyState p").textContent=message;$$('.export-current').forEach(button=>button.disabled=true);setBusy(false,"Auto Schedule");}
async function loadSchedule(){if(busy)return;if(!selectedPackageReady()){showScheduleUnavailable("Select a Ready configuration to load its working schedule.");return;}dirty=false;setBusy(true,"Loading…");try{const res=await fetch(`/api/schedule?package=${encodeURIComponent(selectedPackage())}`),body=await res.json();if(!res.ok)throw new Error(configurationError(body,"Unable to load the configuration schedule"));data=body;baselineData=structuredClone(body);currentResource="";$("#termInput").value=selectedPackage();nextNewInstructorNumber=Math.max(0,...sections().map(r=>String(r.Instructor||"").match(/^(?:Staff|new_instructor)(?:\s+(\d+))?$/i)).filter(Boolean).map(m=>m[1]?+m[1]:1))+1;nextNewProfessorNumber=Math.max(0,...sections().map(r=>String(r.Instructor||"").match(/^new_professor(?:\s+(\d+))?$/i)).filter(Boolean).map(m=>m[1]?+m[1]:1))+1;showApp();renderAll();toast(`Loaded ${body.count} atomic classes from ${body.package_id}.`);}catch(error){showScheduleUnavailable(error.message);toast(error.message,true);}finally{setBusy(false,"Auto Schedule");}}

$("#solveButton").addEventListener("click",async()=>{if(!data||busy)return;setBusy(true,"Scheduling…");try{const res=await fetch("/api/solve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({package:selectedPackage(),records:recordsOf(data)})}),body=await res.json();if(!res.ok)throw new Error(typeof body.detail==="string"?body.detail:"Automatic scheduling failed");data=body;currentResource="";renderAll();markDirty();toast("Scheduling complete. The result can now be saved as a new version.");}catch(e){toast(e.message,true);}finally{setBusy(false,"Auto Schedule");}});

function showApp(){$("#emptyState").classList.add("hidden");$("#app").classList.remove("hidden");$$('.export-current').forEach(button=>button.disabled=false);setBusy(busy);}
$$('.view-tab').forEach(btn=>btn.addEventListener('click',()=>{currentView=btn.dataset.view;currentResource="";$$('.view-tab').forEach(x=>x.classList.toggle('active',x===btn));renderSchedule();}));

function configurationError(body,fallback){const detail=body?.detail;return typeof detail==="string"?detail:detail?.message||fallback;}
function showConfigurationOperationError(message){const problems=$("#configurationProblems");problems.classList.remove("hidden");problems.classList.add("invalid");problems.innerHTML=`<div>${esc(message)}</div>`;toast(message,true);}
function formatUpdatedAt(value){if(!value)return "—";const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleString();}
function renderTemplateStatus(template){$("#configurationTemplateName").textContent=template.present?`更新模板：${template.filename}，${formatUpdatedAt(template.uploaded_at)}`:"No template (default will be generated from courses)";const work=template.work_views||{};$("#configurationTemplateStatus").textContent=template.work_views_present?`Working views: ${work.source||work.role||"existing"}${work.generated_at?` · ${formatUpdatedAt(work.generated_at)}`:""}`:"No working views generated";$("#configurationTemplateDownload").disabled=!template.present;$("#configurationTemplateDelete").disabled=!template.present;$("#configurationTemplateInfer").disabled=!template.present;renderConfigurationDifferences(work.differences);}
function renderConfigurationDifferences(differences){const body=$("#configurationDifferenceBody"),count=$("#configurationDifferenceCount");if(!differences?.available){count.textContent="不可比较";body.innerHTML='<p class="configuration-difference-empty">当前没有可用的 courses 配置，模板内容未与课程配置比较。</p>';return;}const groups=[{title:"模板中多出并被移除",items:differences.removed||[]},{title:"courses 中新增并补入",items:differences.added||[]},{title:"转给动态职位",items:differences.reassigned||[]}],total=groups.reduce((sum,group)=>sum+group.items.length,0);count.textContent=`${total} 项`;body.innerHTML=total?groups.map(group=>`<div class="configuration-difference-group"><strong>${esc(group.title)} (${group.items.length})</strong>${group.items.length?`<ul>${group.items.map(item=>`<li>${esc(item)}</li>`).join("")}</ul>`:'<small>无</small>'}</div>`).join(""):'<p class="configuration-difference-empty">模板与 courses.toml 的课程清单一致。</p>';}
function applyWorkspaceVisibility(){const configuration=currentWorkspace==="configuration";$("#scheduleWorkspace").classList.toggle("hidden",configuration);$("#configurationWorkspace").classList.toggle("hidden",!configuration);$$('.workspace-tab').forEach(tab=>tab.classList.toggle('active',configuration?tab.dataset.workspace==="configuration":tab.dataset.package===selectedPackage()));}
function renderWorkspaceTabs(){const nav=$("#workspaceNav"),available=configurationPackages.filter(item=>item.status==="ready"&&item.working_view_ready);$$('.schedule-package-tab').forEach(tab=>tab.remove());for(const item of available){const tab=document.createElement("button");tab.className="workspace-tab schedule-package-tab";tab.dataset.workspace="schedule";tab.dataset.package=item.id;tab.textContent=item.display_name;nav.append(tab);}if(currentWorkspace==="schedule"&&!available.some(item=>item.id===selectedPackage()))currentWorkspace="configuration";applyWorkspaceVisibility();}
function setWorkspace(name){currentWorkspace=name;applyWorkspaceVisibility();if(name==="configuration")loadConfigurationFiles();}
$("#workspaceNav").addEventListener("click",async event=>{const tab=event.target.closest(".workspace-tab");if(!tab)return;if(tab.dataset.package){$("#packageSelect").value=tab.dataset.package;$("#termInput").value=tab.dataset.package;setWorkspace("schedule");await loadSchedule();return;}setWorkspace("configuration");});
async function loadConfigurationFiles(preferred=""){try{const response=await fetch(`/api/configuration-files?package=${encodeURIComponent(managedPackage())}`),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Unable to load configuration files"));configurationFiles=body.files||[];$("#configurationVersion").textContent=body.config_version||"—";const status=$("#configurationStatus");status.textContent=body.status;status.className=`configuration-status ${body.status}`;const problems=$("#configurationProblems"),messages=body.status==="draft"?(body.missing||[]).map(name=>`Missing: ${name}`):(body.errors||[]);problems.classList.toggle("hidden",!messages.length);problems.classList.toggle("invalid",body.status==="invalid");problems.innerHTML=messages.map(message=>`<div>${esc(message)}</div>`).join("");renderTemplateStatus(body.template||{});configurationDirty=false;renderConfigurationFileList();selectConfigurationFile(preferred||selectedConfigurationName||configurationFiles[0]?.name,true);await loadPackages(managedPackage());}catch(error){toast(error.message,true);}}
function renderConfigurationFileList(){$("#configurationFileList").innerHTML=configurationFiles.map(file=>`<button class="configuration-file-item ${file.name===selectedConfigurationName?"active":""}" data-name="${esc(file.name)}"><strong>${esc(file.name)}</strong><small>${esc(file.present?file.path:"Missing")}</small>${file.present?`<small>最后更新：${esc(formatUpdatedAt(file.updated_at))}</small>`:""}</button>`).join("");}
function selectConfigurationFile(name,force=false){if(configurationDirty&&!force){toast("Save or reset the current file before switching.",true);return;}const file=configurationFiles.find(item=>item.name===name);if(!file)return;selectedConfigurationName=name;configurationDirty=false;$("#configurationFileName").textContent=file.name;$("#configurationFilePath").textContent=file.path;$("#configurationText").value=file.content;$("#configurationText").disabled=!file.present;$("#configurationReset").disabled=true;$("#configurationSave").disabled=true;$("#configurationDeleteFile").disabled=!file.present;$("#configurationGenerateTemplate").classList.toggle("hidden",file.present||!file.template_available);$("#configurationEditStatus").textContent=file.present?"Saved":"Missing";renderConfigurationFileList();}
$("#configurationFileList").addEventListener("click",event=>{const button=event.target.closest(".configuration-file-item");if(button)selectConfigurationFile(button.dataset.name);});
$("#configurationText").addEventListener("input",()=>{const file=configurationFiles.find(item=>item.name===selectedConfigurationName);configurationDirty=!!file&&$("#configurationText").value!==file.content;$("#configurationReset").disabled=!configurationDirty;$("#configurationSave").disabled=!configurationDirty;$("#configurationEditStatus").textContent=configurationDirty?"Unsaved changes":"Saved";});
$("#configurationText").addEventListener("keydown",event=>{if(event.key!=="Tab")return;event.preventDefault();const field=event.target,start=field.selectionStart,end=field.selectionEnd;field.setRangeText("  ",start,end,"end");field.dispatchEvent(new Event("input"));});
$("#configurationReset").addEventListener("click",()=>selectConfigurationFile(selectedConfigurationName,true));
$("#configurationSave").addEventListener("click",async()=>{if(!selectedConfigurationName||!configurationDirty)return;const button=$("#configurationSave");button.disabled=true;button.textContent="Validating…";try{const response=await fetch(`/api/configuration-files/${encodeURIComponent(selectedConfigurationName)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({package:managedPackage(),content:$("#configurationText").value})}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Configuration validation failed"));configurationFiles=body.files||[];$("#configurationVersion").textContent=body.config_version||"—";selectConfigurationFile(selectedConfigurationName,true);toast(`${selectedConfigurationName} validated and saved.`);}catch(error){button.disabled=false;showConfigurationOperationError(error.message);}finally{button.textContent="Validate & Save";}});
async function uploadConfigurationFile(file){if(file)await uploadConfigurationFiles([file]);}
const recognizedConfigurationNames=new Set(["catalogs.toml","locations.toml","timeslot.toml","persons.toml","courses.toml","preferences.toml","constraints.toml"]);
function isScheduleTemplate(file){return /\.(csv|xlsx)$/i.test(file.name);}
async function uploadConfigurationFiles(files){const matched=[...files].filter(file=>recognizedConfigurationNames.has(file.name)||isScheduleTemplate(file));if(!matched.length){toast("No configuration TOMLs or CSV/XLSX template was found.",true);return;}const form=new FormData();matched.forEach(file=>form.append("config_files",file,file.name));form.append("current_package",managedPackage());try{const response=await fetch("/api/configuration-packages",{method:"POST",body:form}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Configuration upload failed"));selectedConfigurationPackage=body.package_id;await loadPackages(body.package_id);await loadConfigurationFiles(recognizedConfigurationNames.has(matched[0].name)?matched[0].name:"");const inferred=body.inferred_files||[];toast(inferred.length?`Updated ${body.package_id}; inferred missing files: ${inferred.join(", ")}.`:`Updated configuration ${body.package_id} with ${matched.length} file(s).`);}catch(error){showConfigurationOperationError(error.message);}}
async function filesFromEntry(entry){if(entry.isFile)return new Promise((resolve,reject)=>entry.file(file=>resolve([file]),reject));if(!entry.isDirectory)return[];const reader=entry.createReader(),entries=[];while(true){const batch=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!batch.length)break;entries.push(...batch);}const nested=await Promise.all(entries.map(filesFromEntry));return nested.flat();}
async function filesFromDrop(dataTransfer){const entries=[...dataTransfer.items].map(item=>item.webkitGetAsEntry?.()).filter(Boolean);if(!entries.length)return[...dataTransfer.files];return(await Promise.all(entries.map(filesFromEntry))).flat();}
$("#configurationFileInput").addEventListener("change",event=>{uploadConfigurationFile(event.target.files[0]);event.target.value="";});
$("#configurationFolderInput").addEventListener("change",event=>{uploadConfigurationFiles(event.target.files);event.target.value="";});
$("#configurationTemplateInput").addEventListener("change",event=>{uploadConfigurationFile(event.target.files[0]);event.target.value="";});
$("#configurationTemplateDownload").addEventListener("click",()=>{location.href=`/api/configuration-packages/${encodeURIComponent(managedPackage())}/template`;});
$("#configurationTemplateDelete").addEventListener("click",async()=>{if(!confirm(`Delete the active template from ${managedPackage()}? It will be moved to trash.`))return;try{const response=await fetch(`/api/configuration-packages/${encodeURIComponent(managedPackage())}/template`,{method:"DELETE"}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Template deletion failed"));await loadConfigurationFiles(selectedConfigurationName);toast("Template moved to trash.");}catch(error){toast(error.message,true);}});
$("#configurationTemplateInfer").addEventListener("click",async()=>{const packageName=managedPackage();if(!confirm(`Create a new 推断(N) configuration from ${packageName}'s template?`))return;const button=$("#configurationTemplateInfer"),old=button.textContent;button.disabled=true;button.textContent="Inferring…";try{const response=await fetch(`/api/configuration-packages/${encodeURIComponent(packageName)}/infer-from-template`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Configuration inference failed"));selectedConfigurationPackage=body.package_id;selectedConfigurationName="";await loadPackages(body.package_id);await loadConfigurationFiles();const count=body.inference||{};toast(`Created ${body.package_id}: ${count.courses||0} courses, ${count.persons||0} people, ${count.relationships||0} relationships.`);}catch(error){showConfigurationOperationError(error.message);}finally{button.textContent=old;button.disabled=false;}});
$("#configurationTemplateRebuild").addEventListener("click",async()=>{const button=$("#configurationTemplateRebuild"),old=button.textContent;button.disabled=true;button.textContent="Rebuilding…";try{const response=await fetch(`/api/configuration-packages/${encodeURIComponent(managedPackage())}/rebuild-work-views`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Working-view rebuild failed"));renderTemplateStatus(body);await loadPackages(managedPackage());toast("Working views rebuilt.");}catch(error){showConfigurationOperationError(error.message);}finally{button.textContent=old;button.disabled=false;}});
const configurationDropzone=$("#configurationDropzone");["dragenter","dragover"].forEach(type=>configurationDropzone.addEventListener(type,event=>{event.preventDefault();configurationDropzone.classList.add("drag-over");}));["dragleave","drop"].forEach(type=>configurationDropzone.addEventListener(type,event=>{event.preventDefault();configurationDropzone.classList.remove("drag-over");}));
configurationDropzone.addEventListener("drop",async event=>uploadConfigurationFiles(await filesFromDrop(event.dataTransfer)));
$("#configurationGenerateTemplate").addEventListener("click",async()=>{try{const response=await fetch(`/api/configuration-packages/${encodeURIComponent(managedPackage())}/templates/${encodeURIComponent(selectedConfigurationName)}`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Template generation failed"));await loadConfigurationFiles(selectedConfigurationName);toast(`Generated ${selectedConfigurationName}.`);}catch(error){toast(error.message,true);}});
$("#configurationDeleteFile").addEventListener("click",async()=>{if(!selectedConfigurationName||!confirm(`Delete ${selectedConfigurationName} from ${managedPackage()}? It will be moved to trash.`))return;try{const response=await fetch(`/api/configuration-packages/${encodeURIComponent(managedPackage())}/files/${encodeURIComponent(selectedConfigurationName)}`,{method:"DELETE"}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"File deletion failed"));await loadConfigurationFiles(selectedConfigurationName);toast(`${selectedConfigurationName} moved to trash.`);}catch(error){toast(error.message,true);}});
$("#configurationDeletePackage").addEventListener("click",async()=>{const packageName=managedPackage();if(data&&packageName===selectedPackage()){toast("This configuration is used by the current schedule and cannot be deleted.",true);return;}if(!confirm(`Delete configuration ${packageName}? It will be moved to trash.`))return;try{const response=await fetch(`/api/configuration-packages/${encodeURIComponent(packageName)}`,{method:"DELETE"}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Configuration deletion failed"));selectedConfigurationName="";selectedConfigurationPackage="";await loadPackages();await loadConfigurationFiles();toast(`${packageName} moved to trash.`);}catch(error){toast(error.message,true);}});
$("#resourceSelect").addEventListener("change",e=>{currentResource=e.target.value;renderScheduleBody();});
$$('.export-current').forEach(button=>button.addEventListener('click',()=>downloadCurrentView(button.dataset.export,button)));
async function downloadCurrentView(view,button){if(!data)return;const old=button.textContent;button.disabled=true;button.textContent="Preparing…";try{const response=await fetch(`/api/export/${view}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({package:selectedPackage(),records:recordsOf(data)})});if(!response.ok){const body=await response.json();throw new Error(configurationError(body,"Export failed"));}const blob=await response.blob(),disposition=response.headers.get("Content-Disposition")||"",match=disposition.match(/filename="([^"]+)"/),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=match?.[1]||`${selectedPackage()}_current_${view}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}catch(error){toast(error.message,true);}finally{button.disabled=false;button.textContent=old;}}

function renderAll(){$("#fileName").textContent=data.source_name||`${selectedPackage()} working schedule`;$("#countLabel").textContent=`${data.count} atomic classes`;renderSchedule();renderWorkload();renderIssues();}

function isPhysical(row){return row["Delivery Mode"]==="in_person";}
// Mirrors Section.delivery_mode (see docs/codes.md) -- the only place this
// tab writes "Time Slot" without also going through this, `Delivery Mode`
// would go stale until the next reload from the backend.
function deliveryModeOf(slot){const s=String(slot||"").toUpperCase();if(s==="ONLINE")return "online";if(s===""||s==="TBA")return "arranged";return "in_person";}
function resources(mode){const rows=mode==="instructor"?sections():sections().filter(isPhysical);const vals=rows.map(r=>mode==="instructor"?(r.Instructor||"Unassigned"):roomLabel(r));if(mode==="instructor")vals.push(...(data.violations?.instructor_loads||[]).map(item=>item.name));return [...new Set(vals)].sort((a,b)=>(mode==="instructor"?instructorLabel(a):a).localeCompare(mode==="instructor"?instructorLabel(b):b,undefined,{sensitivity:"base",numeric:true}));}
function renderSchedule(){const controls=$("#gridControls");if(currentView==="course"){controls.classList.add("hidden");renderCourseList();return;}controls.classList.remove("hidden");const list=resources(currentView);if(!list.includes(currentResource))currentResource=list[0]||"";$("#resourceLabel").textContent=currentView==="instructor"?"Select instructor":"Select room";$("#resourceSelect").innerHTML=list.map(x=>`<option value="${esc(x)}" ${x===currentResource?"selected":""}>${esc(currentView==="instructor"?instructorLabel(x):x)}</option>`).join("");if(!$("#onlineSections"))$("#resourceSelect").insertAdjacentHTML("afterend",'<span id="onlineSections" class="online-sections"></span>');renderScheduleBody();}
function isOnTimeGrid(row){if(!isPhysical(row))return false;const start=startOf(row),days=daysOf(row);return start!=null&&start>=START_MIN&&start<END_MIN&&DAYS.some(([day])=>days.includes(day));}
function renderOnlineSections(){const box=$("#onlineSections");if(!box)return;if(currentView!=="instructor"){box.innerHTML="";box.classList.add("hidden");return;}const unplaced=displaySections().filter(row=>(row.Instructor||"Unassigned")===currentResource&&!isOnTimeGrid(row));box.classList.toggle("hidden",!unplaced.length);box.innerHTML=unplaced.length?`<span class="online-label">Not shown on the timetable</span>${unplaced.map(row=>`<span class="online-chip ${String(row["Time Slot"]||"").toUpperCase()==="TBA"?"tba":""}" data-class="${row._classIndex}" data-record="${row._recordIndex}" title="Right-click to assign · ${esc(row["Time Slot"]||"Unscheduled")}">${esc(row.display_course_id||row.course_id)}</span>`).join("")}`:"";}
function visibleRows(){return displaySections().filter(r=>currentView==="instructor"?(r.Instructor||"Unassigned")===currentResource:roomLabel(r)===currentResource).filter(isOnTimeGrid);}
function conflictIds(){const hard=data.violations?.hard||[],ids=new Set;for(const row of sections()){if(hard.some(item=>item.subject===row.course_id||String(item.message||"").includes(row.course_id)))ids.add(row._id);}return ids;}
function renderScheduleBody(){renderOnlineSections();const rows=visibleRows(),conflicts=conflictIds();let html='<div class="calendar"><div class="cal-corner"></div>'+DAYS.map(d=>`<div class="day-head">${d[1]}</div>`).join("");for(let m=START_MIN;m<END_MIN;m+=STEP){html+=`<div class="time-label">${m%60===0?clock(m):""}</div>`;for(const [day] of DAYS){const blocks=rows.filter(r=>daysOf(r).includes(day)&&Math.floor((startOf(r)-START_MIN)/STEP)*STEP+START_MIN===m);html+=`<div class="drop-cell ${m%60===30?"hour":""}" data-day="${day}" data-minute="${m}">${blocks.map(r=>blockHtml(r,conflicts.has(r._id))).join("")}</div>`;}}html+='</div>';$("#scheduleView").innerHTML=html;bindDrag();}
function blockHtml(r,conflict){const height=Math.max(34,Math.ceil((+r.Duration||STEP)/STEP)*40-4);const secondary=currentView==="instructor"?roomLabel(r):instructorLabel(r.Instructor);return `<div class="course-block${conflict?" conflict":""}" draggable="true" data-class="${r._classIndex}" data-record="${r._recordIndex}" style="height:${height}px"><strong>${esc(r.display_course_id||r.course_id)}</strong><small>${esc(secondary)}</small><small>${esc(clock(startOf(r)))} · ${esc(r.Duration||0)} min</small></div>`;}
function bindDrag(){$$(".course-block").forEach(el=>{el.addEventListener("dragstart",()=>{hideContextMenu();dragged={classIndex:+el.dataset.class,recordIndex:+el.dataset.record};el.classList.add("dragging")});el.addEventListener("dragend",()=>el.classList.remove("dragging"));el.addEventListener("contextmenu",event=>{event.preventDefault();openContextMenu(event,+el.dataset.class,+el.dataset.record);});});$$(".online-chip").forEach(el=>el.addEventListener("contextmenu",event=>{event.preventDefault();openContextMenu(event,+el.dataset.class,+el.dataset.record);}));$$('.drop-cell').forEach(cell=>{cell.addEventListener('dragover',e=>{e.preventDefault();cell.classList.add('drag-over')});cell.addEventListener('dragleave',()=>cell.classList.remove('drag-over'));cell.addEventListener('drop',e=>{e.preventDefault();cell.classList.remove('drag-over');moveSection(+cell.dataset.minute,cell.dataset.day);});});}
function draggedPattern(item,oldDays,targetDay){if(item.kind==="FourCreditClass"){if(oldDays==="MWF")return "MWF";if(["T","R"].includes(oldDays))return "TR".includes(targetDay)?targetDay:oldDays;}if(oldDays==="MWF"&&"TR".includes(targetDay))return "TR";if(oldDays==="TR"&&"MWF".includes(targetDay))return "MWF";return oldDays.length===1?targetDay:oldDays;}
function patternRole(item,row){if(item.kind==="HybridClass")return "hybrid_physical";if(item.kind==="CrossListingClass")return "cross_listing";if(item.kind==="CoreqClass")return (+row.Duration===50&&["MW","TR"].includes(daysOf(row)))?"coreq_supplement":"coreq";return "normal";}
function patternDuration(item,row,newDays){if(newDays===daysOf(row))return +row.Duration||0;const role=patternRole(item,row),patterns=data.assignment_options?.meeting_patterns||[];const match=patterns.find(pattern=>pattern.days===newDays&&pattern.roles.includes(role));return match?.duration||(+row.Duration||0);}
function moveSection(minute,day){if(!dragged)return;const item=data.classes[dragged.classIndex],row=item.sections[dragged.recordIndex],oldSlot=row["Time Slot"],oldDays=daysOf(row);const newDays=draggedPattern(item,oldDays,day),duration=patternDuration(item,row,newDays),value=slotValue(newDays,minute),end=minute+duration,startText=recordClock(minute),endText=recordClock(end);const targets=item.kind==="CrossListingClass"?item.sections.filter(section=>section["Time Slot"]===oldSlot):[row];targets.forEach(section=>{section["Time Slot"]=value;section["Delivery Mode"]=deliveryModeOf(value);section.Days=newDays;section.Duration=duration;section.Start=startText;section.End=endText;});dragged=null;renderScheduleBody();renderIssues();markDirty();toast(`${item.kind==="CrossListingClass"?item.course_ids.join(" / "):courseId(row)} moved to ${value}${newDays!==oldDays?`; pattern ${oldDays} → ${newDays}`:""}`);}
function markDirty(){dirty=true;$("#saveButton").disabled=!selectedPackageReady();$("#statusDot").style.background="#c27a17";$("#countLabel").textContent=`${data.count} atomic classes · Unsaved changes`;scheduleAnalysisRefresh();}
function scheduleAnalysisRefresh(){clearTimeout(analysisTimer);analysisTimer=setTimeout(refreshAnalysis,180);}
async function refreshAnalysis(){if(!data)return;try{const response=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({package:selectedPackage(),records:recordsOf(data)})}),body=await response.json();if(!response.ok)throw new Error(configurationError(body,"Schedule analysis failed"));data.violations=body;renderWorkload();renderIssues();}catch(error){toast(error.message,true);}}

function teacherNames(){const configured=(data.assignment_options?.instructors||[]).filter(name=>!isNewInstructor(name)&&!isNewProfessor(name));return [...new Set([...configured,...sections().map(r=>r.Instructor).filter(Boolean)])].sort((a,b)=>instructorLabel(a).localeCompare(instructorLabel(b),undefined,{sensitivity:"base",numeric:true}));}
function assignedRooms(){const unique=new Map;for(const room of data.assignment_options?.rooms||[]){const label=[room.building,room.room].filter(Boolean).join(" ");if(label)unique.set(label,{label,building:room.building||"",room:room.room});}for(const row of sections()){if(!row.Room)continue;const label=roomLabel(row);if(!unique.has(label))unique.set(label,{label,building:row.Building||"",room:row.Room});}return [...unique.values()].sort((a,b)=>a.label.localeCompare(b.label));}
function openContextMenu(event,classIndex,recordIndex){contextTarget={classIndex,recordIndex};const row=data.classes[classIndex].sections[recordIndex];$("#contextCourse").textContent=courseId(row);$("#contextSlot").textContent=`${row["Time Slot"]||"Unscheduled"} · ${instructorLabel(row.Instructor)} · ${roomLabel(row)}`;$("#contextTeacher").innerHTML=teacherNames().map(name=>`<option value="${esc(name)}" ${name===row.Instructor?"selected":""}>${esc(instructorLabel(name))}</option>`).join("");const rooms=assignedRooms();$("#contextRoom").innerHTML=rooms.map((room,index)=>`<option value="${index}" ${room.room===row.Room&&room.building===(row.Building||"")?"selected":""}>${esc(room.label)}</option>`).join("");const menu=$("#slotContextMenu");menu.classList.remove("hidden");const width=menu.offsetWidth,height=menu.offsetHeight;menu.style.left=`${Math.max(8,Math.min(event.clientX,innerWidth-width-8))}px`;menu.style.top=`${Math.max(8,Math.min(event.clientY,innerHeight-height-8))}px`;}
function hideContextMenu(){contextTarget=null;$("#slotContextMenu").classList.add("hidden");}
function assignTeacher(name){if(!contextTarget||!name)return;const item=data.classes[contextTarget.classIndex],target=item.sections[contextTarget.recordIndex];if(item.kind==="CoreqClass")target.Instructor=name;else item.sections.forEach(row=>row.Instructor=name);markDirty();hideContextMenu();renderSchedule();renderWorkload();renderIssues();toast(`Assigned ${item.kind==="CoreqClass"?courseId(target):item.course_ids.join(" / ")} to ${instructorLabel(name)}`);}
$("#assignTeacher").addEventListener("click",()=>assignTeacher($("#contextTeacher").value));
$("#newInstructor").addEventListener("click",()=>assignTeacher(newInstructorName(nextNewInstructorNumber++)));
$("#newProfessor").addEventListener("click",()=>assignTeacher(newProfessorName(nextNewProfessorNumber++)));
$("#assignRoom").addEventListener("click",()=>{if(!contextTarget)return;const rooms=assignedRooms(),choice=rooms[+$("#contextRoom").value];if(!choice)return;const item=data.classes[contextTarget.classIndex],target=item.sections[contextTarget.recordIndex],slot=target["Time Slot"];item.sections.filter(row=>row["Time Slot"]===slot).forEach(row=>{row.Building=choice.building;row.Room=choice.room;});markDirty();hideContextMenu();renderSchedule();renderIssues();toast(`Assigned ${courseId(target)} to ${choice.label}`);});
document.addEventListener("pointerdown",event=>{if(!event.target.closest("#slotContextMenu")&&!event.target.closest(".course-block"))hideContextMenu();});
document.addEventListener("keydown",event=>{if(event.key==="Escape")hideContextMenu();});
window.addEventListener("resize",hideContextMenu);

function renderCourseList(){const slots=[...new Set(sections().map(r=>r["Time Slot"]).filter(Boolean))].sort();const rows=sections().map(r=>`<div class="course-row"><div class="course-name"><strong>${esc(r.course_id)}</strong><small>${esc(r._item.kind)}</small></div><span>${esc(instructorLabel(r.Instructor))}</span><span>${esc(roomLabel(r))}</span><select class="slot-select" data-class="${r._classIndex}" data-record="${r._recordIndex}">${slots.map(s=>`<option ${s===r["Time Slot"]?"selected":""}>${esc(s)}</option>`).join("")}</select><span>${esc(r.Duration||"—")} min</span></div>`).join("");$("#scheduleView").innerHTML=`<div class="course-list"><div class="course-row header"><span>Course</span><span>Instructor</span><span>Room</span><span>Time Slot</span><span>Duration</span></div>${rows}</div>`;$$('.slot-select').forEach(el=>el.addEventListener('change',()=>{const row=data.classes[+el.dataset.class].sections[el.dataset.record];row['Time Slot']=el.value;row["Delivery Mode"]=deliveryModeOf(el.value);const [days,time]=el.value.split(/\s+/);row.Days=days;row.Start=time;renderIssues();markDirty();toast(`${courseId(row)} time updated`);}));}

function recordsOf(source){return source.classes.flatMap(item=>item.sections.map(row=>Object.fromEntries(Object.entries(row).filter(([key])=>!key.startsWith("_")))));}
$("#saveButton").addEventListener("click",async()=>{if(!data||!baselineData||!dirty||busy)return;const term=selectedPackage();setBusy(true,"Auto Schedule");$("#saveButton").textContent="Publishing…";try{const response=await fetch("/api/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term,package:selectedPackage(),records:recordsOf(data),baseline_records:recordsOf(baselineData)})});const body=await response.json();if(!response.ok){const detail=body.detail;throw new Error(typeof detail==="string"?detail:detail?.message||"Unable to save the version");}dirty=false;$("#statusDot").style.background="";$("#fileName").textContent=`${term}_${body.version}.csv`;$("#countLabel").textContent=`${data.count} atomic classes · Published to ${body.output_dir}`;toast(`Published ${term}/${body.version}`);}catch(error){toast(error.message,true);}finally{$("#saveButton").textContent="Save New Version";setBusy(false,"Auto Schedule");}});

function formatCredits(value){return Number.isInteger(value)?String(value):String(Math.round(value*10)/10);}
function renderWorkload(){const list=data.violations?.instructor_loads||[];$("#totalHours").textContent=`${list.length} instructors`;$("#workloadList").innerHTML=list.map(({name,hours,target,delta,state})=>{const percent=target===null?0:(target<=0?(hours>0?100:0):Math.min(100,hours/target*100)),targetText=target===null?"—":target,label=instructorLabel(name),status=state==="unknown"?"No contract target":state==="exact"?"On target":state==="under"?`Under by ${formatCredits(Math.abs(delta))}`:`Over by ${formatCredits(delta)}`;return `<button type="button" class="load-row load-row-button load-${state}" data-instructor="${esc(name)}" title="View ${esc(label)} schedule"><div class="load-top"><strong>${esc(label)}</strong><span>${hours} / ${targetText} credits</span></div><div class="load-bar"><i style="width:${percent}%"></i></div><div class="load-meta"><span>Contract target ${targetText}</span><span class="load-status">${esc(status)}</span></div></button>`;}).join("");}
$("#workloadList").addEventListener("click",event=>{const row=event.target.closest(".load-row-button");if(!row)return;currentView="instructor";currentResource=row.dataset.instructor;$$('.view-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.view==="instructor"));renderSchedule();});
function softIssue(item){const instructor=item.subject||"Unassigned",matches=[];data.classes.forEach((entry,classIndex)=>{if(!entry.sections.some(row=>row.Instructor===instructor))return;const mentioned=entry.course_ids.filter(id=>String(item.message||"").includes(id));mentioned.forEach(id=>matches.push({label:id,classIndex,view:"instructor",resource:instructor}));});if(matches.length)return {...item,view:"instructor",resource:instructor,courses:matches};const classIndex=data.classes.findIndex(entry=>entry.sections.some(row=>row.Instructor===instructor));return {...item,view:"instructor",resource:instructor,courses:[{label:instructor,classIndex:classIndex>=0?classIndex:"",view:"instructor",resource:instructor}]};}
function renderIssueItem(item){if(!item.courses?.length)return esc(uiText(item.message));const links=item.courses.map(course=>`<a href="#" class="issue-course-link" data-view="${course.view||item.view}" data-resource="${esc(course.resource||item.resource)}" data-class="${course.classIndex}">${esc(course.label)}</a>`).join(" and ");return `${links}: ${esc(uiText(item.message))}`;}
function renderIssues(){const hard=data.violations?.hard||[],soft=(data.violations?.soft||[]).map(softIssue),orange=soft.filter(x=>x.severity==="orange"),yellow=soft.filter(x=>x.severity!=="orange");const total=hard.length+soft.length;$("#healthSummary").innerHTML=`<span class="health-badge ${hard.length?"bad":""}">${hard.length?`${hard.length} hard conflicts`:`${total?soft.length+" items to review":"Schedule healthy"}`}</span>`;const group=(level,title,items)=>`<div class="issue-group ${level}"><div class="issue-title"><i class="issue-dot"></i>${title} (${items.length})</div>${items.length?`<ul>${items.slice(0,8).map(x=>`<li>${renderIssueItem(x)}</li>`).join("")}</ul>`:'<ul><li>None</li></ul>'}</div>`;$("#violationsSummary").innerHTML=`<div class="violations">${group("red","Current Conflicts",hard)}${group("orange","High-Priority Preferences",orange)}${group("yellow","Unmet Preferences",yellow)}</div>`;}
$("#violationsSummary").addEventListener("click",event=>{const link=event.target.closest(".issue-course-link");if(!link)return;event.preventDefault();currentView=link.dataset.view;currentResource=link.dataset.resource;$$('.view-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.view===currentView));renderSchedule();requestAnimationFrame(()=>{if(link.dataset.class==="")return;const block=$(`.course-block[data-class="${link.dataset.class}"]`);if(!block)return;block.scrollIntoView({behavior:"smooth",block:"center",inline:"center"});const oldShadow=block.style.boxShadow;block.style.boxShadow="0 0 0 3px #e69a2d, 0 4px 14px rgba(0,0,0,.2)";setTimeout(()=>block.style.boxShadow=oldShadow,1800);});});
